name: Build & Deploy

on:
  push:
    branches:
      - sushitimebkt.gihm.com.np

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sushitimebkt-development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SUSHI_TIME_BKT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Makefile
        run: |
          make web
        env:
          PUSHER_APP_KEY: ${{ secrets.SUSHI_TIME_BKT_PUSHER_KEY }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_APP_PATH: ${{ secrets.SSH_APP_PATH }}
          SSH_API_PATH: ${{ secrets.SSH_API_PATH }}
